<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a36895b4-46aa-4ac4-9112-6035a12b0a4f</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(12) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(5) &gt; :nth-child(1) &gt; :nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-outline-secondary text-center')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-outline-secondary text-center</value>
        <webElementGuid>90e3b1fa-2e38-4a7e-9457-29ea500f0641</webElementGuid>
    </webElementProperties>
</WebElementEntity>